name: "run-git-sumi"
description: "Use git-sumi to validate a PR title"
author: "Óscar <osc@osc.garden>"

branding:
  icon: 'search'
  color: 'purple'

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v5
      with:
        sparse-checkout: .  # Check out only repository root, where 'sumi.toml' is located.

    - name: Download git-sumi binary
      shell: bash
      run: |
        curl -L "https://github.com/welpo/git-sumi/releases/download/v0.2.0/git-sumi-x86_64-unknown-linux-gnu.tar.xz" -o git-sumi.tar.xz

    - name: Extract and rename git-sumi binary
      shell: bash
      run: |
        tar -xf git-sumi.tar.xz
        mv git-sumi-x86_64-unknown-linux-gnu/git-sumi git-sumi
        chmod +x git-sumi

    - name: Run git-sumi
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      shell: bash
      run: |
        export GIT_SUMI_QUIET=false
        output=$(./git-sumi -f table "${PR_TITLE}")
        exit_code=$?

        if [ $exit_code -eq 0 ]; then
          # Command succeeded. Format the output.
          content=$(echo "$output" | awk '/\| Key/,0' | head -n -1)
          last_line=$(echo "$output" | tail -n 1)
          {
            echo "## git-sumi"
            echo "$content"  # This is the Markdown table.
            echo ""
            echo "$last_line"  # Summary.
          } >> "${GITHUB_STEP_SUMMARY}"
        fi
