name: "run-git-sumi"
description: "Use git-sumi to validate a PR title"
author: "Óscar <osc@osc.garden>"

branding:
  icon: 'search'
  color: 'purple'

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: .  # Check out only repository root.

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install --quiet git-sumi

    - name: Run git-sumi
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      shell: bash
      run: |
        git-sumi "${PR_TITLE}"
