name: "run-git-sumi"
description: "Use git-sumi to validate a PR title"
author: "Óscar <osc@osc.garden>"

branding:
  icon: 'search'
  color: 'purple'

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: .  # Check out only repository root, where 'sumi.toml' is located.

    - name: Install git-sumi
      uses: baptiste0928/cargo-install@v3
      with:
        crate: git-sumi

    - name: Run git-sumi
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      shell: bash
      run: |
        git-sumi "${PR_TITLE}"
